#services:
#  mongodb:
#    image: mongo
#    container_name: mongo_db
#    ports:
#      - 27017:27017
#    volumes:
#      - mongo:/data/db
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=nampd
#      - MONGO_INITDB_ROOT_PASSWORD=nam.pd193034@
#  mongo-express:
#    image: mongo-express
#    container_name: mongo_express
#    restart: always
#    ports:
#      - 8081:8081
#    depends_on:
#      - mongodb
#    environment:
#      - ME_CONFIG_MONGODB_ADMINUSERNAME=nampd
#      - ME_CONFIG_MONGODB_ADMINPASSWORD=nam.pd193034@
#      - ME_CONFIG_MONGODB_SERVER=mongodb
#volumes:
#  mongo: {}
